name: latlong
description: Lightweight library for common latitude and longitude calculation
homepage: https://github.com/MikeMitterer/dart-latlong

version: 0.6.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logging: ^1.1.0
  validate: ^1.7.0

  intl: '>=0.15.0 <1.0.0'

dev_dependencies:
  test: any
  build_runner: any
  build_test: any
  build_web_compilers: any
